CafeShop/CafeShop/CafeShop/Controllers/AboutController.cs
using CafeShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace CafeShop.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {

            return View();
        }
    }
}

CafeShop/CafeShop/CafeShop/Controllers/CartController.cs
using CafeShop.Models;
using CafeShop.Models.DTOs;
using CafeShop.Reposiory;
using ManagementCourse.Common;
using Microsoft.AspNetCore.Mvc;

namespace CafeShop.Controllers
{
    public class CartController : Controller
    {
        public CartRepository _repo = new CartRepository();
        public AccountRepository _accRepo = new AccountRepository();
        public IActionResult Index()
        {
            Account acc = _accRepo.GetByID(HttpContext.Session.GetInt32("AccountId") ?? 0) ?? new Account();
            if(acc.Id <= 0)
            {
                return Redirect("/Shop/Index");
            }
            ViewBag.Account = acc;
            return View();
        }
        public JsonResult GetCartByAccountId()
        {
            Account acc = _accRepo.GetByID(HttpContext.Session.GetInt32("AccountId") ?? 0) ?? new Account();
            if (acc.Id <= 0)
            {
                return Json(new {status=0, massage="Đăng nhập để sử dụng tính năng!"});
            }
            List<CartDto> lst = SQLHelper<CartDto>.ProcedureToList("spGetCartByAccountId",
                                                                    new string[] { "@AccountId" },
                                                                    new object[] { acc.Id});
            if(lst.Count == 0) return Json(new { status = 2, massage = "Bạn chưa có sản phẩm nào trong giỏ hàng!"});

            return Json(new { status = 1, massage = "",data = lst });

        }
        public async Task<JsonResult> AddToCart(int productDetailId, int accountId, int quantity = 1)
        {
            try
            {
                if(accountId <= 0) return Json(new { status = 0, message = "Hãy đăng nhập để sử dụng tính năng này!" });
                if(productDetailId <= 0) return Json(new { status = 0, message = "Hãy chọn size sản phẩm!" });


                List<Cart> lst = SQLHelper<Cart>.SqlToList($"SELECT * FROM Cart WHERE AccountId = {accountId}");
                Cart model = lst.FirstOrDefault(x => x.ProductDetailId == productDetailId ) ?? new Cart();
                if (model.Id > 0)
                {
                    model.Quantity = model.Quantity + quantity;
                    _repo.Update(model);
                }
                else
                {
                    model.ProductDetailId = productDetailId;
                    model.AccountId = accountId;
                    model.Quantity = quantity;
                    await _repo.CreateAsync(model);
                }

                return Json(new { status = 1, message = "Thêm vào giỏ hàng thành công!"});
            }
            catch (Exception ex)
            {

                return Json(new { status = 0, message = ex.Message});
            }
            
        }


        public async Task<JsonResult> RemoveToCart(int cartId, int quantity = 1)
        {
            try
            {
                Cart model = _repo.GetByID(cartId) ?? new Cart();
                if (model.Id > 0)
                {
                    if(model.Quantity > quantity)
                    {
                        model.Quantity = model.Quantity - quantity;
                        _repo.Update(model);
                    }
                    else
                    {
                        _repo.Delete(model.Id);
                    }
                }
                else
                {
                    return Json(new { status = 0, message = "Không thể tìm thấy sản phẩm trong giỏ hàng!" });

                }

                return Json(new { status = 1, message = "Cập nhật giỏ hàng thành công!" });
            }
            catch (Exception ex)
            {

                return Json(new { status = 0, message = ex.Message });
            }

        }
    }
}

CafeShop/CafeShop/CafeShop/Controllers/OrderController.cs
using CafeShop.Models;
using CafeShop.Models.DTOs;
using CafeShop.Reposiory;
using ManagementCourse.Common;
using Microsoft.AspNetCore.Mvc;

namespace CafeShop.Controllers
{
    public class OrderController : Controller
    {
        public AccountRepository _accRepo = new AccountRepository();
        public OrderRepository _repo = new OrderRepository();
        public OrderDetailsRepository _detailRepo = new OrderDetailsRepository();
        public IActionResult Index()
        {
            Account acc = _accRepo.GetByID(HttpContext.Session.GetInt32("AccountId") ?? 0) ?? new Account();
            if (acc.Id <= 0)
            {
                return Redirect("/Shop/Index");
            }

            return View();
        }

        public IActionResult OrderDetails(int OrderId = 0)
        {
            Account acc = _accRepo.GetByID(HttpContext.Session.GetInt32("AccountId") ?? 0) ?? new Account();
            if (acc.Id <= 0)
            {
                return Redirect("/Shop/Index");
            }
            ViewBag.Order = _repo.GetByID(OrderId) ?? new Order();
            List<OrderDetailsDto> lst = SQLHelper<OrderDetailsDto>.ProcedureToList("spGetOrderDetails",
                                                                                    new string[] { "@OrderId" },
                                                                                    new object[] { OrderId });
            ViewBag.Details = lst;

            int totalMoney = 0;
            foreach (var item in lst)
            {
                totalMoney += item.TotalMoney;
            }
            ViewBag.Total = totalMoney;

            return View();
        }
        public JsonResult GetAll(string request = "")
        {
            Account acc = _accRepo.GetByID(HttpContext.Session.GetInt32("AccountId") ?? 0) ?? new Account();
            if (acc.Id <= 0)
            {
                return Json(new { status = 0, message = "Hãy đăng nhập để sử dụng tính năng này!" });
            }
            List<OrderDto> lst = SQLHelper<OrderDto>.ProcedureToList("spGetHistoryCheckOut",
                                                                      new string[] { "@AccountId", "@Request" },
                                                                      new object[] { acc.Id , request});
            foreach (var item in lst)
            {
                item.DateFormat = item.CreateDate.ToString("dd/MM/yyyy HH:mm:ss");
            }
            return Json(new { status = 1, message = "", data = lst});
        }
        [HttpPost]
        public async Task<JsonResult> CreateOrder([FromBody] OrderDto data)
        {
            try
            {
                Account accout = _accRepo.GetByID(data.AccountId) ?? new Account();
                if (accout.Id <= 0) return Json(new { status = 0, message = "Đăng nhập để sử dụng tính năng này!" });
                int currentYear = DateTime.Now.Year;
                List<Order> lst = SQLHelper<Order>.SqlToList($"SELECT * FROM [Order] WHERE YEAR(CreateDate) = {currentYear}");

                Order newOrder = new Order();

                newOrder.OrderCode = $"MHĐ{currentYear}CFS{lst.Count + 1}";
                newOrder.CustomerName = data.CustomerName;
                newOrder.PhoneNumber = data.PhoneNumber;
                newOrder.Address = data.Address;
                newOrder.Status = 0;
                newOrder.CreateDate = DateTime.Now;
                newOrder.CreateBy = accout.FullName;
                newOrder.AccountId = data.AccountId;

                await _repo.CreateAsync(newOrder);


                if (data.Details == null || data.Details.Count <= 0) return Json(new { status = 0, message = "Hãy chọn ít nhất 1 sản phẩm để tạo đơn hàng!" });
                foreach (var item in data.Details)
                {
                    OrderDetail newOderDetails = new OrderDetail();
                    newOderDetails.Quantity = item.Quantity;
                    newOderDetails.TotalMoney = item.TotalMoney;
                    newOderDetails.ProductDetailId = item.ProductDetailId;
                    newOderDetails.OrderId = newOrder.Id;
                    _detailRepo.Create(newOderDetails);
                }

                SQLHelper<Cart>.SqlToModel($"DELETE FROM Cart WHERE AccountID = {accout.Id}");

                return Json(new { status = 1, message = "Đặt hàng thành công!" });
            }
            catch (Exception ex)
            {

                return Json(new { status = 0, message = ex.Message });
            }

        }
    }
}

CafeShop/CafeShop/CafeShop/Controllers/ShopController.cs
using Azure.Core;
using CafeShop.Common;
using CafeShop.Models;
using CafeShop.Models.DTOs;
using CafeShop.Reposiory;
using ManagementCourse.Common;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Routing;
using System.Diagnostics.CodeAnalysis;

namespace CafeShop.Controllers
{
    public class ShopController : Controller
    {
        public AccountRepository _accRepo = new AccountRepository();
        public ProductTypeRepository _prType = new ProductTypeRepository();
        public ProductRepository _prRepo = new ProductRepository();
        public ProductImageRepository _prImg = new ProductImageRepository();
        public ProductDetailsRepository _prDt = new ProductDetailsRepository();

        public IActionResult Index()
        {
            Account acc = _accRepo.GetByID(HttpContext.Session.GetInt32("AccountId") ?? 0) ?? new Account();
            ViewBag.Account = acc;
            return View();
        }
        public JsonResult GetAllProductType()
        {
            List<ProductType> Coffe = SQLHelper<ProductType>.SqlToList("SELECT * FROM ProductType WHERE GroupType = 1");
            List<ProductType> Tea = SQLHelper<ProductType>.SqlToList("SELECT * FROM ProductType WHERE GroupType = 2");
            List<ProductType> Different = SQLHelper<ProductType>.SqlToList("SELECT * FROM ProductType WHERE GroupType = 3");

            return Json(new { Coffe, Tea, Different });
        }
        public JsonResult GetALlProduct(int typeId = 0, string request = "", int pageNumber = 1)
        {
            List<ProductDto> data = SQLHelper<ProductDto>.ProcedureToList("spGetAllProductClient", new string[] { "@typeId", "@Request", "@PageNumber" }, new object[] { typeId, request, pageNumber });
            PaginationDto total = SQLHelper<PaginationDto>.ProcedureToModel("spGetAllTotalProductClient", new string[] { "@typeId", "@Request" }, new object[] { typeId, request });
            return Json(new { status = 1, message = "", result = new { data , total } });

        }

        public IActionResult IndexDetails(int prId)
        {
            Account acc = _accRepo.GetByID(HttpContext.Session.GetInt32("AccountId") ?? 0) ?? new Account();
            ViewBag.Account = acc;

            ViewBag.Product = _prRepo.GetByID(prId);

            List<ProductImage> lstImg = SQLHelper<ProductImage>.SqlToList($"select * from ProductImage where ProductID = {prId}");
            foreach (ProductImage img in lstImg)
            {
                img.ImageUrl = Config.ImageUrl() + img.ImageUrl;
            }
            ViewBag.Avatar = lstImg[0];
            ViewBag.Image = lstImg;

            List<ProductSizeDto> lstSize = SQLHelper<ProductSizeDto>.ProcedureToList("spGetProductSizeById", new string[] { "@ProductId" }, new object[] { prId });
            ViewBag.ProductSize = lstSize;
            ViewBag.PriceDefault = Convert.ToInt32(lstSize[0].Price).ToString("N0");

            List<ProductDto> lst = SQLHelper<ProductDto>.ProcedureToList("spGetAllProductClient", new string[] { "@typeId", "@Request", "@PageNumber" }, new object[] { ViewBag.Product.ProductTypeId, "", 1 });
            ViewBag.ProductRelated = lst.Where(p => p.Id != ViewBag.Product.Id);
            return View();
        }
    }
}

CafeShop/CafeShop/CafeShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["CafeShop"] - CafeShop</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CafeShop.styles.css" asp-append-version="true" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/templatemo.min.css" rel="stylesheet" />

    <link href="~/css/fontawesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin="" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
@{
    var FullName = Context.Session.GetString("FullName");
    var Id = Context.Session.GetInt32("AccountId");
    var Role = Context.Session.GetInt32("AccountRole");
}
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light shadow">
            <div class="container d-flex justify-content-between align-items-center">

                <a class="navbar-brand text-success logo h2 align-self-center" asp-controller="Home" asp-action="Index" style="white-space: nowrap">
                    Coffe Shop
                </a>

                <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
                    <div class="flex-fill">
                        <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="Index">Trang chủ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="About" asp-action="Index">Giới thiệu</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Shop" asp-action="Index">Cửa hàng</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Contact" asp-action="Index">Liên hệ</a>
                            </li>
                        </ul>
                    </div>
                    <div class="navbar align-self-center d-flex">
                        <div class="d-lg-none flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3 pe-1">
                        </div>
                        @if(Id > 0)
                        {
                            <a class="nav-icon position-relative text-decoration-none" asp-controller="Cart" asp-action="Index">
                                <i class="bi bi-cart-check-fill"></i>
                            </a>
                        }
                        else
                        {
                            <a class="nav-icon position-relative text-decoration-none" href="#" onclick="alert('Đăng nhập để sử dụng tính năng này!')">
                                <i class="bi bi-cart-check-fill"></i>
                            </a>
                        }
                        

                        <div class="nav-icon position-relative text-decoration-none">
                            <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                                <ul class="navbar-nav">
                                    <li class="nav-item dropdown">
                                        <i class="bi bi-person-fill dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"></i>
                                        @if(Id > 0)
                                        {
                                            <ul class="dropdown-menu dropdown-menu" style="position: absolute; top: 40px; left: -70px;">
                                                <li><a class="dropdown-item" href="#">@FullName</a></li>
                                                <li><a class="dropdown-item" asp-controller="Order" asp-action="Index">Lịch sử mua hàng</a></li>
                                                @if(Role == 2)
                                                {
                                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Home" asp-action="Index">Quản lý</a></li>
                                                }
                                                <li><a class="dropdown-item" asp-controller="Home" asp-action="Privacy">Đăng xuất</a></li>
                                            </ul>
                                        }
                                        else
                                        {
                                            <ul class="dropdown-menu dropdown-menu" style="position: absolute; top: 30px; left: -70px;">
                                                <li><a class="dropdown-item" asp-controller="Home" asp-action="Privacy">Đăng nhập</a></li>
                                                <li><a class="dropdown-item" asp-controller="Account" asp-action="Register">Đăng ký</a></li>
                                            </ul>
                                        }
                                        
                                    </li>
                                </ul>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </nav>
    </header>
    <div class="container mb-3">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="bg-dark" id="tempaltemo_footer">
        <div class="container">
            <div class="row">

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-success border-bottom pb-3 border-light logo">Coffe Shop</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li>
                            <i class="bi bi-geo-alt"></i>
                            123 Consectetur at ligula 10660
                        </li>
                        <li>
                            <i class="bi bi-telephone"></i>
                            <a class="text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
                        </li>
                        <li>
                            <i class="bi bi-envelope"></i>
                            <a class="text-decoration-none" href="mailto:info@company.com">info@company.com</a>
                        </li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Sản phẩm</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" href="#">Trà</a></li>
                        <li><a class="text-decoration-none" href="#">Cà phê</a></li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Thông tin</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" href="#">Trang chủ</a></li>
                        <li><a class="text-decoration-none" href="#">Giới thiệu</a></li>
                        <li><a class="text-decoration-none" href="#">Địa chỉ cửa hàng</a></li>
                        <li><a class="text-decoration-none" href="#">Câu hỏi thường gặp</a></li>
                        <li><a class="text-decoration-none" href="#">Liên hệ</a></li>
                    </ul>
                </div>

            </div>

            <div class="row text-light mb-4">
                <div class="col-12 mb-3">
                    <div class="w-100 my-3 border-top border-light"></div>
                </div>
                <div class="col-auto me-auto">
                    <ul class="list-inline text-left footer-icons">
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="http://facebook.com/"><i class="bi bi-facebook text-light"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://www.instagram.com/"><i class="bi bi-instagram text-light"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://twitter.com/"><i class="bi bi-twitter-x text-light"></i></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://www.linkedin.com/"><i class="bi bi-youtube text-light"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-auto">
                    <label class="sr-only" for="subscribeEmail">Email </label>
                    <div class="input-group mb-2">
                        <input type="text" class="form-control bg-dark border-light" id="subscribeEmail" placeholder="Email ">
                        <div class="input-group-text btn-success text-light">Đăng ký</div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery-1.11.0.min.js"></script>
    <script src="~/js/jquery-migrate-1.2.1.min.js"></script>
    <script src="~/js/templatemo.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>